version: 2
updates:
  - package-ecosystem: "npm" # or "pip", "docker", "maven", etc.
    directory: "/"           # location of manifest file
    schedule:
      interval: "daily"     # or "daily", "monthly"
