os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        use:
          name: 7july_500k52_01
      script: 
        - echo "read"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
